{% set name = "environment_settings" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/environment_settings-{{ version }}.tar.gz
  sha256: d0c8ab0ce6b6f08a089d877a2f52acf4efaf4821cf6890161637af2768b294d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - environment_settings
  commands:
    - pip check
  requires:
    - pip
    - pytest >=6.2.0

about:
  home: https://github.com/m0nonoke/environment-settings
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Environment specific management of application configuration
  description: "Environment specific management of application configuration"
  doc_url: https://github.com/m0nonoke/environment-settings

extra:
  recipe-maintainers:
    - m0nonoke
